apiVersion: v1
kind: Secret
metadata:
  name: tenant-cluster
  namespace: kamaji-system
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
type: Opaque
data:
  cacert: ""
  clouds.yaml: Y2xvdWRzOgogIG9wZW5zdGFjay1zdGFnZToKICAgIGF1dGg6CiAgICAgIGF1dGhfdXJsOiBodHRwczovL2lhYXMtdnAtaW50ZXJuYWwuZGlnaWNsb3VkLmlyOjUwMDAvdjMKICAgICAgYXBwbGljYXRpb25fY3JlZGVudGlhbF9pZDogOThiNGI0MTNlYTY1NGUzNzkwYTYyMzBiY2I0YWM5NTQKICAgICAgYXBwbGljYXRpb25fY3JlZGVudGlhbF9zZWNyZXQ6IDIyM2Q1ZTk5YjViNTg5MjA3MDQ3MDRmMAogICAgYXV0aF90eXBlOiB2M2FwcGxpY2F0aW9uY3JlZGVudGlhbAogICAgcmVnaW9uX25hbWU6IGlyLXZhbmFrLXBsYXphCiAgICBpbnRlcmZhY2U6IHB1YmxpYwogICAgaWRlbnRpdHlfYXBpX3ZlcnNpb246IDM=
